apiVersion : apps/v1
kind: Deployment
metadata:
 name: consumerdeployment
 labels:
  app: consumerdeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: consumer
 template:
  metadata:
   labels:
    app: consumer
  spec:
   containers:
     - image: arshabbir/consumer:latest
       name : consumer
       imagePullPolicy: Always
       env:
        - name: CLUSTERIP 
          value : "cassandra"
        - name: PORT
          value : ":8081"
        - name: KAFKA_HOST
          value : "172.31.38.67:29092"
        - name: TOPIC
          value :  "myTopic1"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
    
    - port: 8081
      targetPort: 8081
      nodePort: 30007



